# mappings:
#   PerfectCmsImageValidator: Sunnysideup\PerfectCmsImages\Filesystem\PerfectCmsImageValidator
#   PerfectCmsImagesBuildTaskCheckImages: Sunnysideup\PerfectCmsImages\Tasks\PerfectCmsImagesBuildTaskCheckImages
#   PerfectCmsImageDataExtension: Sunnysideup\PerfectCmsImages\Model\File\PerfectCmsImageDataExtension
#   PerfectCmsImagesUploadField: Sunnysideup\PerfectCmsImages\Forms\PerfectCmsImagesUploadField
