---
Name: perfect_cms_images
---
SilverStripe\Assets\Image:
  extensions:
    - Sunnysideup\PerfectCmsImages\Model\File\PerfectCmsImageDataExtension

SilverStripe\Assets\File:
  file_types:
    svg: 'SVG Image'
    webp: 'Webp Image'
  allowed_extensions:
    - svg
    - webp
  app_categories:
    image:
      - svg
      - webp
    image/supported:
      - svg
      - webp
  class_for_file_extension:
    svg: SilverStripe\Assets\Image
    webp: SilverStripe\Assets\Image

SilverStripe\Assets\Storage\DBFile:
  supported_images:
    - image/svg
    - image/svg+xml
    - image/webp

SilverStripe\MimeValidator\MimeUploadValidator:
  MimeTypes:
    svg:
      - 'image/svg+xml'
      - 'image/svg'
    webp:
      - 'image/webp'

Axllent\ScaledUploads\ScaledUploads:
  max_width: 2800 # Maximum width - default 960
  max_height: 1867 # Maximum height - default 800
  auto_rotate: true # Automatically rotate images that rely on exif information for rotation - default true
  bypass: false # Bypass (skip) this plugin when uploading - default false
  force_resampling: true # Force re-saving the image even if it is smaller - default false
